### ISSUE TITLE
Chrome on Android freezes when uses text tools

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1993]
If I open a long text , eg/dn2 using Chrome on Android, it all works fine. Then if I enable line-by-line view, Chrome crashes. Not just the tab, the whole app. 

The line-by-line text is showing just fine. But clearly something is going bad.

It's true that this is a big page and it will be a fairly large load. However on the old site it works just fine. There, the changing views is a lot more complicated, and uses much more JS. So normally the line-by-line change takes considerably longer. nevertheless, it doesn't freeze up or cause any problems other than a delay.

This is Chrome 88, Android 11, Pixel 3XL. It's been a persistent problem for a while.

**Comment by robertmusil** [comment]
This actually works for me on Chrome 88, Android 11, Pixel 4a.
I go to https://staging.suttacentral.net/dn2/en/sujato enable line-by-line and any number of other options and it's working, maybe fixed now?

**Comment by sujato** [comment]
It's still freezing for me, I've cleared site data and loaded in incognito, on en/mn23 it crashes when I change the Pali script. This is not a very big sutta. On a very short sutta like sn2.2 there is no problem.

On dn2 if I go to "plain" view it just doesn't work, it still shows English and Pali. But at least it's not crashing!

**Comment by ihongda** [comment]
Switching to `linebyline` and `sidebyside` triggers a layout style change for the page, which needs to be re-rendered, no problem on the PC, but it's a little slower on the phone side, but on my `iPhone 6s chrome87, Meizu pro7 plus (android 7)`, there's no freeze for the time being :)

**Comment by sujato** [comment]
This problem seems to be fixed.
