### ISSUE TITLE
Some links are not styled properly, very problematic on dark theme

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/suttacentral#2979]
- [x] Donation Success page
- [ ] [Donate now page](https://suttacentral.net/donate-now)
- [x] search results (e.g. https://staging.suttacentral.net/search?query=dh%C4%ABt%C4%81%20AND%20daughter)
- [ ] SERP input box label. (possibly on hold)

#### Description:

Links on some pages are not styled properly. This especially leads to problems on dark theme.

#### Steps to reproduce:

This is the [Donation success page](https://suttacentral.net/donation-success) on light mode:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/73023d4e-5ffe-47c0-84ce-7aec77a85a48)

On Dark mode:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/209930e0-ea82-481f-9aa8-40752b559fd8)

On dark mode once link is visited:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/d284afbd-acf8-4376-b959-3be8620b8aeb)

#### Expected behaviour:

This is what links look like on the rest of the site:
![image](https://github.com/suttacentral/suttacentral/assets/82448383/4442e0fc-e035-4cb3-b236-4dc4bac0523d)

**Comment by thesunshade** [comment]
I have no idea if this is the problem, but I notice in `sc-static-donation-success.js`  it does not import `typographyStaticStyles`.


Also, there is this bit in `sc-static-donation-success.js` :

```js
  static styles = [
    layoutSimpleStyles,
    typographyCommonStyles,
```

But that other static pages don't have that. Instead they have this (e.g. `static-introduction.js`:

```js
  render() {
    return html`
      <style>
        ${layoutSimpleStyles}
        ${typographyCommonStyles}
        ${typographyStaticStyles}
      </style>
      <main>
        <article>
```

I did find that the `offline` static page looks right on the front end and has this:
```js
  static styles = [
    layoutSimpleStyles,
    typographyCommonStyles,
    SCUtilityStyles,
```

And `SCUtilityStyles.js` does seem to have the styling for links. So that could be the missing bit.

**Comment by thesunshade** [comment]
OK, the [Donate now page](https://suttacentral.net/donate-now) has the same issue with the links and appears to have similar code to the donation success page

**Comment by sabbamitta** [comment]
Thank you for tracking all these down, Bhante. There are likely more pages affected. I posted some occurrences in the main "dev" thread, but these are all a while back, and it might not be easy to unearth them all. But perhaps there is an easier way to find all cases by searching the code.

**Comment by ihongda** [comment]
Thanks @thesunshade @sabbamitta 
I'll see if I can find all the styles that don't match expectations. 🙏🏼

**Comment by thesunshade** [comment]
@ihongda I just noticed that the links in search results excerpts have this problem:

![image](https://github.com/suttacentral/suttacentral/assets/82448383/76ad5112-be37-4cdb-81b7-eb7db8d14927)

**Comment by ihongda** [comment]
I believe this problem has been fixed @thesunshade

**Comment by thesunshade** [comment]
It looks like the problem still exists on the [Donate now page](https://suttacentral.net/donate-now).

Also, I noticed the same issue on the quick search interface ("Search in all texts" here, but "Input search term" on staging.):

![image](https://github.com/suttacentral/suttacentral/assets/82448383/4277aecb-b1a7-43ac-99f1-2a08f906192f)

**Comment by ihongda** [comment]
![screenshot_2024-02-23_23-27-49](https://github.com/suttacentral/suttacentral/assets/4037966/aaefc8c4-97da-4913-8e99-ed7fd71c428d)

Like this style?

**Comment by thesunshade** [comment]
> Like this style?

I just rely on accessibility contrast testers:
https://coolors.co/contrast-checker/f9b20f-616161
![image](https://github.com/suttacentral/suttacentral/assets/82448383/b3d9bf98-b0e3-4f6f-b573-381cd9d081cf)

So this fails on small text and is just passing on regular text.

There are loads of plugins and testers online.

The background color of the input box is already so light that almost anything but white text is going to be hard to get it to pass.

Looking at this for so long, I'd actually like to propose a complete change of this interface that could solve a few different problems. I'll make an issue.

Maybe for now just leave the search input as is until I propose an alternative design?

That just leaves the [Donate now page](https://suttacentral.net/donate-now)

**Comment by thesunshade** [comment]
OK, I have created an issue suggesting a small (??) redesign to the search input field that would eliminate the problem with the search box label https://github.com/suttacentral/suttacentral/issues/3028
